### ISSUE TITLE
Random disconnect when using the websocket connection

### ISSUE THREAD

**Issue by PaxxPatriot** [PaxxPatriot/skinport.py#3]
When using the websocket connection it can happen that the library disconnects from it.

Found in [PaxxPatriot/cheapbot #1](https://github.com/PaxxPatriot/cheapbot/issues/1)

```
packet queue is empty, aborting
Traceback (most recent call last):
  File "C:\Users\lukas\skinport.py.bot\cheapbot.py", line 38, in <module>
    skinport_client.run()
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\skinport\client.py", line 132, in run
    return future.result()
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\skinport\client.py", line 111, in runner
    await self.connect(*args, **kwargs)
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\skinport\client.py", line 194, in connect
    await self.ws.connect("https://skinport.com", transports=["websocket"])
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\socketio\asyncio_client.py", line 117, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
```

**Comment by PaxxPatriot** [comment]
This was fixed by #4
